#include "textures.h"
#include <GL/gl.h>
#include <SDL2/SDL.h>

static const int numTextures = 72;
static char *texturePaths[]{
    "./data/PenguinBody.bmp",
    "./data/PenguinFeet.bmp",
    "./data/Smoke.bmp",
    "./data/Marble.bmp",
    "./data/Blue/Torso.bmp",
    "./data/Bluepurple.bmp",
    "./data/Blue/Helmet.bmp",
    "./data/Blue/Upperarm.bmp",
    "./data/Blue/Lowerleg.bmp",
    "./data/Blue/Shoes.bmp",
    "./data/Rope.bmp",
    "./data/Grid.bmp",
    "./data/Star.bmp",
    "./data/Red/Torso.bmp",
    "./data/Red/Shoes.bmp",
    "./data/Red/Helmet.bmp",
    "./data/Red/Upperarm.bmp",
    "./data/Red/Lowerleg.bmp",
    "./data/Green/Torso.bmp",
    "./data/Green/Shoes.bmp",
    "./data/Green/Helmet.bmp",
    "./data/Green/Upperarm.bmp",
    "./data/Green/Lowerleg.bmp",
    "./data/Yellow/Torso.bmp",
    "./data/Yellow/Shoes.bmp",
    "./data/Yellow/Helmet.bmp",
    "./data/Yellow/Upperarm.bmp",
    "./data/Yellow/Lowerleg.bmp",
    "./data/Metal.bmp",
    "./data/Matrix.bmp",
    "./data/MatrixDark.bmp",
    "./data/MetalMesh.bmp",
    "./data/LaserRifle.bmp",
    "./data/Black/Torso.bmp",
    "./data/Black/Shoes.bmp",
    "./data/Black/Helmet.bmp",
    "./data/Black/Upperarm.bmp",
    "./data/Black/Lowerleg.bmp",
    "./data/Laser.bmp",
    "./data/LaserFront.bmp",
    "./data/MachineGun.bmp",
    "./data/Sword.bmp",
    "./data/Rifle.bmp",
    "./data/Island/Right.bmp",
    "./data/Island/Back.bmp",
    "./data/Island/Left.bmp",
    "./data/Island/Front.bmp",
    "./data/Island/Down.bmp",
    "./data/Island/Up.bmp",
    "./data/Jetpack.bmp",
    "./data/LightSabre.bmp",
    "./data/LightBlade.bmp",
    "./data/LightBladeFront.bmp",
    "./data/SmokePuff.bmp",
    "./data/Lava/Right.bmp",
    "./data/Lava/Back.bmp",
    "./data/Lava/Left.bmp",
    "./data/Lava/Front.bmp",
    "./data/Lava/Down.bmp",
    "./data/Lava/Up.bmp",
    "./data/Snowy/Right.bmp",
    "./data/Snowy/Back.bmp",
    "./data/Snowy/Left.bmp",
    "./data/Snowy/Front.bmp",
    "./data/Snowy/Down.bmp",
    "./data/Snowy/Up.bmp",
    "./data/Grenskin.bmp",
    "./data/Grenade.bmp",
    "./data/LightningGun.bmp",
    "./data/Lightning.bmp",
    "./data/BladeTrail.bmp",
    "./data/Font.bmp",
};

int loadTextures() {}

void freeTextures() {}

void bindTexture(int id) {}
